### PR TITLE
Remove #[cfg(unix)] for std::io::Error foreign_link

### LINKED ISSUE #4: serde::export::From<std::io::Error> not implemented
When building with nightly rust on Windows, I get the following error:

```
> rustc --version
rustc 1.22.0-nightly (4502e2aa9 2017-10-03)
```

```
> cargo build
error[E0277]: the trait bound `errors::Error: serde::export::From<std::io::Error>` is not satisfied
  --> world\src\mapfile.rs:39:5
   |
39 |     write!(output, "{}", MapSave { map, legend })?;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::export::From<std::io::Error>` is not implemented for `errors::Error`
   |
   = help: the following implementations were found:
             <errors::Error as serde::export::From<ron::ser::Error>>
             <errors::Error as serde::export::From<ron::de::Error>>
             <errors::Error as serde::export::From<errors::ErrorKind>>
             <errors::Error as serde::export::From<&'a str>>
             <errors::Error as serde::export::From<std::string::String>>
   = note: required by `serde::export::From::from`
```

Is this an easy fix? I'm still learning `error_chain` and Rust in general.

### PR DESCRIPTION
**Pull request by kevinw**
Fixes #4 on Windows.

### CODE REVIEW

**Comment by rsaarelm** [comment]
Thanks.

**Comment by rsaarelm** [comment]
Oh, hey, one more thing, can you agree to transfer the copyrights to this and whatever future PRs you submit to me? I need to set up a proper contributor instruction system to this effect...

**Comment by rsaarelm** [comment]
Oh, hey, one more thing, can you agree to transfer the copyrights to this and whatever future PRs you submit to me? I need to set up a proper contributor instruction system to this effect... I figure just replying "yes" here should be good enough for now.

**Comment by kevinw** [comment]
Yes

**Pull request merged**
